### ISSUE TITLE
Not working if helper is empty at init

### ISSUE THREAD

**Issue by alexandrepa** [SirYasko/HA-Blueprints#1]
I was trying to use your blueprint zha-adeo-lxek5-zbek26.yaml without success until I manually add a json context in my helper text variable.

If helper is empty (normal behavior the first time we create an automation with this blueprint) this line fail : 

` v__entity_JSON:     '{{ (states(v__entity_helper) | from_json) }}'`

I'm not really used to HASS script syntax, maybe can be a quick fix for you. If no I could take some time to fix it.

By the way thanks for this great contribution.

**Comment by SirYasko** [comment]
You could overwrite empty helper by selecting scene button with assigned entity - so it shouldn't be a huge problem.
Additionally I've added protection against empty helper (you could test it - v2.1)
